apiVersion: v1
kind: Service
metadata:
  name: realm-keeper-backend
  labels:
    app: realm-keeper-backend
    app.kubernetes.io/name: realm-keeper-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: realm-keeper
spec:
  type: ClusterIP
  selector:
    app: realm-keeper-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
