apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realm-keeper-backend-pdb
  labels:
    app: realm-keeper-backend
    app.kubernetes.io/name: realm-keeper-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: realm-keeper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: realm-keeper-backend
