apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-keeper-backend-config
  labels:
    app: realm-keeper-backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: realm-keeper
data:
  REPO_URL: "https://github.com/ArnauFauquer/RealmKeeperVault.git"
  NOTE_TAG_IGNORE: "draft"
  VAULT_SYNC_INTERVAL: "3600"
  CORS_ALLOWED_ORIGINS: "https://realmkeeper.faukinator.com"
  OLLAMA_HOST: "http://ollama.ollama.svc.cluster.local:11434"
  LLM_MODEL: "llama3.1:8b-instruct-q4_0"
  EMBEDDING_MODEL: "nomic-embed-text"
  EMBEDDING_DIM: "768"
  LLM_CONTEXT_SIZE: "8192"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-keeper-frontend-config
  labels:
    app: realm-keeper-frontend
    app.kubernetes.io/name: realm-keeper-frontend
    app.kubernetes.io/part-of: realm-keeper
data:
  VITE_API_URL: "https://realmkeeper.faukinator.com"
  VITE_ALLOWED_HOSTS: "realmkeeper.faukinator.com"
