apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realm-keeper-frontend-pdb
  labels:
    app: realm-keeper-frontend
    app.kubernetes.io/name: realm-keeper-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: realm-keeper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: realm-keeper-frontend
