apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realm-keeper-rag-storage-pvc
  labels:
    app: realm-keeper-backend
    app.kubernetes.io/name: realm-keeper-backend
    app.kubernetes.io/part-of: realm-keeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
